import Foundation

/// Human names and expected payload sizes for the service 01 PIDs this library decodes.
public struct PIDDescriptor: Sendable {
    public let name: String
    public let byteCount: Int

    public static func named(_ pid: UInt8) -> String {
        table[pid]?.name ?? "PID \(String(format: "%02X", pid))"
    }

    public static let table: [UInt8: PIDDescriptor] = [
        0x00: .init(name: "Supported PIDs 01-20", byteCount: 4),
        0x01: .init(name: "Monitor status since DTCs cleared", byteCount: 4),
        0x02: .init(name: "Freeze frame DTC", byteCount: 2),
        0x03: .init(name: "Fuel system status", byteCount: 2),
        0x04: .init(name: "Calculated engine load", byteCount: 1),
        0x05: .init(name: "Coolant temperature", byteCount: 1),
        0x06: .init(name: "Short term fuel trim, bank 1", byteCount: 1),
        0x07: .init(name: "Long term fuel trim, bank 1", byteCount: 1),
        0x08: .init(name: "Short term fuel trim, bank 2", byteCount: 1),
        0x09: .init(name: "Long term fuel trim, bank 2", byteCount: 1),
        0x0A: .init(name: "Fuel pressure", byteCount: 1),
        0x0B: .init(name: "Intake manifold pressure", byteCount: 1),
        0x0C: .init(name: "Engine RPM", byteCount: 2),
        0x0D: .init(name: "Vehicle speed", byteCount: 1),
        0x0E: .init(name: "Timing advance", byteCount: 1),
        0x0F: .init(name: "Intake air temperature", byteCount: 1),
        0x10: .init(name: "MAF air flow rate", byteCount: 2),
        0x11: .init(name: "Throttle position", byteCount: 1),
        0x12: .init(name: "Commanded secondary air status", byteCount: 1),
        0x13: .init(name: "Oxygen sensors present (2 banks)", byteCount: 1),
        0x14: .init(name: "O2 sensor 1", byteCount: 2),
        0x15: .init(name: "O2 sensor 2", byteCount: 2),
        0x16: .init(name: "O2 sensor 3", byteCount: 2),
        0x17: .init(name: "O2 sensor 4", byteCount: 2),
        0x18: .init(name: "O2 sensor 5", byteCount: 2),
        0x19: .init(name: "O2 sensor 6", byteCount: 2),
        0x1A: .init(name: "O2 sensor 7", byteCount: 2),
        0x1B: .init(name: "O2 sensor 8", byteCount: 2),
        0x1C: .init(name: "OBD standard", byteCount: 1),
        0x1D: .init(name: "Oxygen sensors present (4 banks)", byteCount: 1),
        0x1E: .init(name: "Auxiliary input status", byteCount: 1),
        0x1F: .init(name: "Run time since engine start", byteCount: 2),
        0x20: .init(name: "Supported PIDs 21-40", byteCount: 4),
        0x21: .init(name: "Distance with MIL on", byteCount: 2),
        0x22: .init(name: "Fuel rail pressure (relative)", byteCount: 2),
        0x23: .init(name: "Fuel rail gauge pressure", byteCount: 2),
        0x24: .init(name: "O2 sensor 1 (wide range)", byteCount: 4),
        0x25: .init(name: "O2 sensor 2 (wide range)", byteCount: 4),
        0x26: .init(name: "O2 sensor 3 (wide range)", byteCount: 4),
        0x27: .init(name: "O2 sensor 4 (wide range)", byteCount: 4),
        0x28: .init(name: "O2 sensor 5 (wide range)", byteCount: 4),
        0x29: .init(name: "O2 sensor 6 (wide range)", byteCount: 4),
        0x2A: .init(name: "O2 sensor 7 (wide range)", byteCount: 4),
        0x2B: .init(name: "O2 sensor 8 (wide range)", byteCount: 4),
        0x2C: .init(name: "Commanded EGR", byteCount: 1),
        0x2D: .init(name: "EGR error", byteCount: 1),
        0x2E: .init(name: "Commanded evaporative purge", byteCount: 1),
        0x2F: .init(name: "Fuel tank level", byteCount: 1),
        0x30: .init(name: "Warm-ups since DTCs cleared", byteCount: 1),
        0x31: .init(name: "Distance since DTCs cleared", byteCount: 2),
        0x32: .init(name: "Evap system vapor pressure", byteCount: 2),
        0x33: .init(name: "Barometric pressure", byteCount: 1),
        0x3C: .init(name: "Catalyst temperature, bank 1 sensor 1", byteCount: 2),
        0x3D: .init(name: "Catalyst temperature, bank 2 sensor 1", byteCount: 2),
        0x3E: .init(name: "Catalyst temperature, bank 1 sensor 2", byteCount: 2),
        0x3F: .init(name: "Catalyst temperature, bank 2 sensor 2", byteCount: 2),
        0x40: .init(name: "Supported PIDs 41-60", byteCount: 4),
        0x41: .init(name: "Monitor status this drive cycle", byteCount: 4),
        0x42: .init(name: "Control module voltage", byteCount: 2),
        0x43: .init(name: "Absolute load value", byteCount: 2),
        0x44: .init(name: "Commanded equivalence ratio", byteCount: 2),
        0x45: .init(name: "Relative throttle position", byteCount: 1),
        0x46: .init(name: "Ambient air temperature", byteCount: 1),
        0x47: .init(name: "Absolute throttle position B", byteCount: 1),
        0x48: .init(name: "Absolute throttle position C", byteCount: 1),
        0x49: .init(name: "Accelerator pedal position D", byteCount: 1),
        0x4A: .init(name: "Accelerator pedal position E", byteCount: 1),
        0x4B: .init(name: "Accelerator pedal position F", byteCount: 1),
        0x4C: .init(name: "Commanded throttle actuator", byteCount: 1),
        0x4D: .init(name: "Time run with MIL on", byteCount: 2),
        0x4E: .init(name: "Time since DTCs cleared", byteCount: 2),
        0x51: .init(name: "Fuel type", byteCount: 1),
        0x52: .init(name: "Ethanol fuel percentage", byteCount: 1),
        0x5C: .init(name: "Engine oil temperature", byteCount: 1),
        0x5D: .init(name: "Fuel injection timing", byteCount: 2),
        0x5E: .init(name: "Engine fuel rate", byteCount: 2),
        0x60: .init(name: "Supported PIDs 61-80", byteCount: 4),
        0x80: .init(name: "Supported PIDs 81-A0", byteCount: 4),
        0xA0: .init(name: "Supported PIDs A1-C0", byteCount: 4),
        0xC0: .init(name: "Supported PIDs C1-E0", byteCount: 4),
    ]
}
