import Foundation
import OBDCore

/// The vehicle identity used to match a bounded catalog platform.
public struct CatalogVehicle: Codable, Sendable, Equatable, Hashable {
    public let make: String
    public let model: String
    public let year: Int

    public init(make: String, model: String, year: Int) {
        self.make = make
        self.model = model
        self.year = year
    }
}

public enum ModuleProvenance: String, Codable, Sendable, Equatable {
    case observed
    case reference
}

public struct CatalogModule: Sendable, Equatable {
    public let label: String
    public let target: ModuleTarget
    public let provenance: ModuleProvenance
    public let source: String
}

public struct CatalogPlatform: Sendable, Equatable {
    public let name: String
    public let modules: [CatalogModule]
}

public enum ModuleCatalogError: Error, Equatable, Sendable, CustomStringConvertible {
    case unsupportedSchemaVersion(Int)
    case malformed(String)
    case unknownBus(String)
    case unknownProvenance(String)
    case invalidTarget(String)
    case duplicateTarget(String)
    case invalidYearRange
    case emptyField(String)
    case duplicateMake(String)

    public var description: String {
        switch self {
        case .unsupportedSchemaVersion(let version):
            return "module catalog schema version \(version) is not supported"
        case .malformed(let detail): return "malformed module catalog: \(detail)"
        case .unknownBus(let bus): return "module catalog has unknown bus \"\(bus)\""
        case .unknownProvenance(let provenance):
            return "module catalog has unknown provenance \"\(provenance)\""
        case .invalidTarget(let target): return "module catalog has invalid target \"\(target)\""
        case .duplicateTarget(let target): return "module catalog repeats target \"\(target)\""
        case .invalidYearRange:
            return "module catalog has a year range whose first year is after its last"
        case .emptyField(let field): return "module catalog has an empty \(field)"
        case .duplicateMake(let make): return "module catalog lists the make \"\(make)\" twice"
        }
    }
}

/// Bounded, shipped make and platform knowledge. This is data, not a vehicle discovery result.
///
/// Two files ship: `modules.json`, what Spia has seen on cars, and `modules-opendbc.json`,
/// addresses openpilot recorded on real cars, generated by `scripts/import-opendbc.py`. A car
/// gets every platform of its make that lists its model for its year, Spia's own first.
public struct ModuleCatalog: Sendable, Equatable {
    public let schemaVersion: Int
    public let catalogVersion: String
    public let makes: [Make]

    public struct Make: Sendable, Equatable {
        public let make: String
        public let aliases: [String]
        public let platforms: [Platform]
    }

    public struct Platform: Sendable, Equatable {
        public let name: String
        public let models: [String]
        public let firstYear: Int
        public let lastYear: Int
        public let modules: [CatalogModule]
        public let source: String?
    }

    public init(data: Data) throws {
        let raw: RawCatalog
        do {
            raw = try JSONDecoder().decode(RawCatalog.self, from: data)
        } catch {
            throw ModuleCatalogError.malformed(error.localizedDescription)
        }
        guard raw.schemaVersion == 1 else {
            throw ModuleCatalogError.unsupportedSchemaVersion(raw.schemaVersion)
        }
        guard !raw.catalogVersion.isEmpty else {
            throw ModuleCatalogError.emptyField("catalog version")
        }
        try self.init(
            schemaVersion: raw.schemaVersion, catalogVersion: raw.catalogVersion,
            makes: raw.makes.map(Self.make))
    }

    private init(schemaVersion: Int, catalogVersion: String, makes: [Make]) throws {
        try Self.checkDistinctMakes(makes)
        self.schemaVersion = schemaVersion
        self.catalogVersion = catalogVersion
        self.makes = makes
    }

    public static func bundled() throws -> ModuleCatalog {
        try load("modules").merging(load("modules-opendbc"))
    }

    private static func load(_ name: String) throws -> ModuleCatalog {
        guard
            let url = Bundle.module.url(
                forResource: name, withExtension: "json", subdirectory: "Catalog")
        else { throw ModuleCatalogError.malformed("bundled \(name).json is missing") }
        return try ModuleCatalog(data: Data(contentsOf: url))
    }

    /// This catalog with `other`'s makes added: a make both know keeps this catalog's name and
    /// platforms first, so `match` prefers this catalog's modules and their names.
    public func merging(_ other: ModuleCatalog) throws -> ModuleCatalog {
        var merged = makes
        for make in other.makes {
            let names = Set(([make.make] + make.aliases).map(Self.normalize))
            if let index = merged.firstIndex(where: {
                !names.isDisjoint(with: ([$0.make] + $0.aliases).map(Self.normalize))
            }) {
                let known = merged[index]
                let knownNames = Set(([known.make] + known.aliases).map(Self.normalize))
                merged[index] = Make(
                    make: known.make,
                    aliases: known.aliases
                        + ([make.make] + make.aliases).filter {
                            !knownNames.contains(Self.normalize($0))
                        },
                    platforms: known.platforms + make.platforms)
            } else {
                merged.append(make)
            }
        }
        return try ModuleCatalog(
            schemaVersion: schemaVersion,
            catalogVersion: "\(catalogVersion)+\(other.catalogVersion)", makes: merged)
    }

    /// Every platform of the vehicle's make that lists its model for its year, as one: the first
    /// platform, with the modules of all of them in catalog order without repeating a target, so
    /// the first's labels win. Platforms may overlap on purpose: opendbc lists a Sonata and a
    /// Sonata Hybrid apart, and NHTSA decodes both as a Sonata.
    public func match(_ vehicle: CatalogVehicle) -> Platform? {
        let make = Self.normalize(vehicle.make)
        let model = Self.normalize(vehicle.model)
        let fitting =
            makes.first(where: {
                Self.normalize($0.make) == make
                    || $0.aliases.contains { Self.normalize($0) == make }
            })?
            .platforms.filter {
                $0.models.contains { Self.normalize($0) == model }
                    && ($0.firstYear...$0.lastYear).contains(vehicle.year)
            } ?? []
        guard let first = fitting.first else { return nil }
        var seen = Set<ModuleTarget>()
        return Platform(
            name: first.name, models: first.models, firstYear: first.firstYear,
            lastYear: first.lastYear,
            modules: fitting.flatMap(\.modules).filter { seen.insert($0.target).inserted },
            source: first.source)
    }

    private static func make(_ raw: RawMake) throws -> Make {
        guard !normalize(raw.make).isEmpty, raw.aliases.allSatisfy({ !normalize($0).isEmpty })
        else { throw ModuleCatalogError.emptyField("make") }
        guard !raw.platforms.isEmpty else { throw ModuleCatalogError.emptyField("platforms") }
        return Make(
            make: raw.make, aliases: raw.aliases,
            platforms: try raw.platforms.map(Self.platform))
    }

    /// `match` takes the first make that fits, so a make listed twice would leave the later one
    /// unused.
    private static func checkDistinctMakes(_ makes: [Make]) throws {
        var names = Set<String>()
        for make in makes {
            for name in [make.make] + make.aliases {
                guard names.insert(normalize(name)).inserted else {
                    throw ModuleCatalogError.duplicateMake(name)
                }
            }
        }
    }

    private static func platform(_ raw: RawPlatform) throws -> Platform {
        guard !raw.name.isEmpty else { throw ModuleCatalogError.emptyField("platform name") }
        guard !raw.models.isEmpty, raw.models.allSatisfy({ !normalize($0).isEmpty }) else {
            throw ModuleCatalogError.emptyField("models")
        }
        guard raw.years.first <= raw.years.last else {
            throw ModuleCatalogError.invalidYearRange
        }
        guard !raw.modules.isEmpty else { throw ModuleCatalogError.emptyField("modules") }
        var seen = Set<ModuleTarget>()
        let modules = try raw.modules.map { module -> CatalogModule in
            guard !module.label.isEmpty else { throw ModuleCatalogError.emptyField("module label") }
            guard let bus = CANBus(rawValue: module.bus) else {
                throw ModuleCatalogError.unknownBus(module.bus)
            }
            guard let provenance = ModuleProvenance(rawValue: module.provenance) else {
                throw ModuleCatalogError.unknownProvenance(module.provenance)
            }
            guard let request = UInt32(module.request, radix: 16),
                let reply = UInt32(module.reply, radix: 16)
            else { throw ModuleCatalogError.invalidTarget("\(module.request) -> \(module.reply)") }
            let target: ModuleTarget
            do { target = try ModuleTarget(bus: bus, request: request, response: reply) } catch {
                throw ModuleCatalogError.invalidTarget(error.localizedDescription)
            }
            guard seen.insert(target).inserted else {
                throw ModuleCatalogError.duplicateTarget("\(module.request) -> \(module.reply)")
            }
            return CatalogModule(
                label: module.label, target: target, provenance: provenance, source: module.source)
        }
        return Platform(
            name: raw.name, models: raw.models, firstYear: raw.years.first,
            lastYear: raw.years.last, modules: modules, source: raw.source)
    }

    private static func normalize(_ value: String) -> String {
        var result = ""
        var space = false
        for scalar in value.unicodeScalars {
            if scalar.properties.isAlphabetic || scalar.properties.numericType != nil {
                if space && !result.isEmpty { result.append(" ") }
                result.append(String(scalar).lowercased())
                space = false
            } else {
                space = true
            }
        }
        return result.trimmingCharacters(in: .whitespaces)
    }
}

private struct RawCatalog: Decodable {
    let schemaVersion: Int
    let catalogVersion: String
    let makes: [RawMake]
}

private struct RawMake: Decodable {
    let make: String
    let aliases: [String]
    let platforms: [RawPlatform]
}

private struct RawPlatform: Decodable {
    let name: String
    let models: [String]
    let years: RawYears
    let modules: [RawModule]
    let source: String?
}

private struct RawYears: Decodable {
    let first: Int
    let last: Int
}

private struct RawModule: Decodable {
    let label: String
    let bus: String
    let request: String
    let reply: String
    let provenance: String
    let source: String
}
